![image](https://pwskills.com/images/PWSkills-main.png)

# Data Science Masters

## Day - 26
## Date- 26 February 2023 
## Numpy - I

In [1]:
import numpy as np

In [2]:
l= [1, 2, 3, 4]

In [3]:
ar= np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a= [2, 3, 4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b= np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c= a  

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0]= 100

In [19]:
c

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
d= np.copy(a)

In [22]:
d

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
a[1]= 400

In [25]:
a

array([100, 400,   3,   4])

In [26]:
d

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [32]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

## Numpy - Data Types.

In [33]:
l= [2, 3, 4, 5, 6]

In [34]:
ar= np.array(l)

In [35]:
ar

array([2, 3, 4, 5, 6])

In [36]:
ar.ndim

1

In [37]:
ar2= np.array([[1,2,3,4], [2,3,4,5]])

In [38]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [39]:
ar2.ndim

2

In [40]:
ar.size

5

In [41]:
ar2.size

8

In [42]:
ar

array([2, 3, 4, 5, 6])

In [43]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [44]:
ar.shape

(5,)

In [45]:
ar2.shape

(2, 4)

In [46]:
ar.dtype

dtype('int64')

In [47]:
ar2.dtype


dtype('int64')

In [48]:
ar22= np.array([(1.4,45,45) , (23,45,66)])

In [49]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [50]:
ar22.dtype

dtype('float64')

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [54]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [55]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [59]:
ar4 = np.zeros((3,4,2,3))

In [60]:
ar4.ndim


4

In [61]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [62]:
np.ones(4)

array([1., 1., 1., 1.])

In [63]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
on= np.ones((2, 3, 2))

In [65]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [66]:
on *4


array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [67]:
np.empty((3, 6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [68]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
np.linspace(2, 4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [70]:
np.logspace(2, 5, 10, base= 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [71]:
arr = np.random.randn(3, 4)

In [72]:
import pandas as pd 

In [73]:
pd.DataFrame(arr)

0         1         2         3
0 -0.431046  1.172821  1.293044  0.963238
1 -1.666450  0.124789  1.306670  1.793698
2 -2.175002 -0.312968 -0.817195 -0.960724

In [74]:
np.random.rand(3, 4)

array([[0.81972142, 0.3521492 , 0.97302122, 0.84543185],
       [0.24383044, 0.42353264, 0.73645579, 0.62110192],
       [0.24621002, 0.90489389, 0.7310567 , 0.26094415]])

In [75]:
pd.DataFrame(np.random.randint(1, 110, (300, 400))).to_csv('test.csv')

In [76]:
arr= np.random.rand(3, 4)

In [77]:
arr

array([[0.57362641, 0.44911488, 0.87384372, 0.02698534],
       [0.42729951, 0.94778279, 0.17786741, 0.55444866],
       [0.22477664, 0.67255129, 0.24179251, 0.54416123]])

In [78]:
arr.reshape(6, -1)

array([[0.57362641, 0.44911488],
       [0.87384372, 0.02698534],
       [0.42729951, 0.94778279],
       [0.17786741, 0.55444866],
       [0.22477664, 0.67255129],
       [0.24179251, 0.54416123]])

In [79]:
arr1= arr.reshape(6, -134353553435)

In [80]:
arr1

array([[0.57362641, 0.44911488],
       [0.87384372, 0.02698534],
       [0.42729951, 0.94778279],
       [0.17786741, 0.55444866],
       [0.22477664, 0.67255129],
       [0.24179251, 0.54416123]])

In [81]:
arr1[1][1]

0.02698534495963012

In [82]:
arr1[2:5,1]

array([0.94778279, 0.55444866, 0.67255129])

In [83]:
arr= np.random.randint(1,100 , (5,5))

In [84]:
arr

array([[83, 28, 47, 46, 85],
       [11, 34, 30, 12, 32],
       [43, 96, 31, 91,  4],
       [98, 23, 96, 63, 10],
       [74, 20, 94, 99, 32]])

In [85]:
arr[arr>50]

array([83, 85, 96, 91, 98, 96, 63, 74, 94, 99])

In [86]:
arr

array([[83, 28, 47, 46, 85],
       [11, 34, 30, 12, 32],
       [43, 96, 31, 91,  4],
       [98, 23, 96, 63, 10],
       [74, 20, 94, 99, 32]])

In [87]:
arr[2:4 , [1,2]]

array([[96, 31],
       [23, 96]])

In [88]:
arr[0][0] = 5000

In [89]:
arr

array([[5000,   28,   47,   46,   85],
       [  11,   34,   30,   12,   32],
       [  43,   96,   31,   91,    4],
       [  98,   23,   96,   63,   10],
       [  74,   20,   94,   99,   32]])

In [90]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [91]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [92]:
arr2


array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [93]:
arr1+arr2

array([[3, 2, 3],
       [3, 3, 3],
       [2, 4, 2]])

In [94]:
arr1-arr2

array([[ 1,  0,  1],
       [ 1, -1, -1],
       [ 0,  0,  0]])

In [95]:
arr1/arr2

array([[2. , 1. , 2. ],
       [2. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [96]:
arr1 * arr2

array([[2, 1, 2],
       [2, 2, 2],
       [1, 4, 1]])

In [97]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [98]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [99]:
arr1@arr2

array([[5, 8, 6],
       [4, 6, 5],
       [4, 7, 6]])

In [100]:
arr1/0

/tmp/ipykernel_172/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [101]:
arr1 +100

array([[102, 101, 102],
       [102, 101, 101],
       [101, 102, 101]])

In [102]:
arr1**2

array([[4, 1, 4],
       [4, 1, 1],
       [1, 4, 1]])

## Numpy – Broadcasting.

In [103]:
arr=np.zeros((4, 4))

In [104]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
row= np.array([1,2,3,4])

In [106]:
row.shape

(4,)

In [107]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [108]:
row.T

array([1, 2, 3, 4])

In [109]:
col= np.array([[1, 2, 3, 4]])

In [110]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [111]:
col

array([[1, 2, 3, 4]])

In [112]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
arr1 = np.random.randint(1, 4, (3, 4))

In [114]:
arr1

array([[3, 1, 3, 1],
       [3, 3, 2, 2],
       [3, 1, 3, 2]])

In [115]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.73205081, 1.        ],
       [1.73205081, 1.73205081, 1.41421356, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.41421356]])

In [116]:
np.exp(arr1)

array([[20.08553692,  2.71828183, 20.08553692,  2.71828183],
       [20.08553692, 20.08553692,  7.3890561 ,  7.3890561 ],
       [20.08553692,  2.71828183, 20.08553692,  7.3890561 ]])

In [117]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.47712125, 0.        ],
       [0.47712125, 0.47712125, 0.30103   , 0.30103   ],
       [0.47712125, 0.        , 0.47712125, 0.30103   ]])