![image](https://pwskills.com/images/PWSkills-main.png)

# Data Science Masters

## Day - 26
## Date- 26 February 2023 
## Numpy - II

## Numpy - Array Manipulation.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, (3,4))

In [3]:
arr

array([[1, 5, 4, 3],
       [2, 5, 9, 9],
       [4, 7, 7, 5]])

In [4]:
arr.reshape(6, 2)

array([[1, 5],
       [4, 3],
       [2, 5],
       [9, 9],
       [4, 7],
       [7, 5]])

In [5]:
arr.reshape(2, 6)

array([[1, 5, 4, 3, 2, 5],
       [9, 9, 4, 7, 7, 5]])

In [6]:
arr.reshape(2, -242342)

array([[1, 5, 4, 3, 2, 5],
       [9, 9, 4, 7, 7, 5]])

In [7]:
arr.T

array([[1, 2, 4],
       [5, 5, 7],
       [4, 9, 7],
       [3, 9, 5]])

In [8]:
arr

array([[1, 5, 4, 3],
       [2, 5, 9, 9],
       [4, 7, 7, 5]])

In [9]:
arr.flatten()

array([1, 5, 4, 3, 2, 5, 9, 9, 4, 7, 7, 5])

In [10]:
arr1= np.array([1, 2, 3, 3, 4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [14]:
arr

array([[1, 5, 4, 3],
       [2, 5, 9, 9],
       [4, 7, 7, 5]])

In [15]:
np.squeeze(arr)

array([[1, 5, 4, 3],
       [2, 5, 9, 9],
       [4, 7, 7, 5]])

In [16]:
data = np.array([[1], [2], [3]])

In [17]:
data

array([[1],
       [2],
       [3]])

In [18]:
np.squeeze(data)

array([1, 2, 3])

In [19]:
arr1

array([1, 2, 3, 3, 4])

In [20]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [21]:
np.roll(arr1 , 3)

array([3, 3, 4, 1, 2])

In [22]:
arr1

array([1, 2, 3, 3, 4])

In [23]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

## Numpy - Binary Operators.

In [24]:
arr1 = np.random.randint(1, 10, (3,4))

In [25]:
arr2 = np.random.randint(1, 10, (3,4))

In [26]:
arr1

array([[4, 5, 4, 3],
       [2, 9, 1, 6],
       [8, 7, 9, 2]])

In [27]:
arr2

array([[1, 5, 9, 1],
       [6, 3, 8, 5],
       [1, 6, 3, 9]])

In [28]:
arr1+arr2

array([[ 5, 10, 13,  4],
       [ 8, 12,  9, 11],
       [ 9, 13, 12, 11]])

In [29]:
arr1*arr2

array([[ 4, 25, 36,  3],
       [12, 27,  8, 30],
       [ 8, 42, 27, 18]])

In [30]:
arr1/arr2

array([[4.        , 1.        , 0.44444444, 3.        ],
       [0.33333333, 3.        , 0.125     , 1.2       ],
       [8.        , 1.16666667, 3.        , 0.22222222]])

In [31]:
arr1-arr2

array([[ 3,  0, -5,  2],
       [-4,  6, -7,  1],
       [ 7,  1,  6, -7]])

In [32]:
arr1%arr2

array([[0, 0, 4, 0],
       [2, 0, 1, 1],
       [0, 1, 0, 2]])

In [33]:
arr1 ** arr2

array([[     4,   3125, 262144,      3],
       [    64,    729,      1,   7776],
       [     8, 117649,    729,    512]])

In [34]:
arr1 & arr2

array([[0, 5, 0, 1],
       [2, 1, 0, 4],
       [0, 6, 1, 0]])

In [35]:
arr1

array([[4, 5, 4, 3],
       [2, 9, 1, 6],
       [8, 7, 9, 2]])

In [36]:
arr2

array([[1, 5, 9, 1],
       [6, 3, 8, 5],
       [1, 6, 3, 9]])

In [37]:
~arr1

array([[ -5,  -6,  -5,  -4],
       [ -3, -10,  -2,  -7],
       [ -9,  -8, -10,  -3]])

In [38]:
arr1|arr2

array([[ 5,  5, 13,  3],
       [ 6, 11,  9,  7],
       [ 9,  7, 11, 11]])

In [39]:
arr1>arr2

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [ True,  True,  True, False]])

## Numpy - String Functions.

In [40]:
arr= np.array(['Mohammad', "Wasiq"])

In [41]:
arr

array(['Mohammad', 'Wasiq'], dtype='<U8')

In [42]:
np.char.upper(arr)

array(['MOHAMMAD', 'WASIQ'], dtype='<U8')

In [43]:
np.char.title(arr)

array(['Mohammad', 'Wasiq'], dtype='<U8')

In [44]:
np.char.capitalize(arr)

array(['Mohammad', 'Wasiq'], dtype='<U8')

## Numpy - Mathematical Functions.

In [45]:
arr1

array([[4, 5, 4, 3],
       [2, 9, 1, 6],
       [8, 7, 9, 2]])

In [46]:
np.sin(arr1)

array([[-0.7568025 , -0.95892427, -0.7568025 ,  0.14112001],
       [ 0.90929743,  0.41211849,  0.84147098, -0.2794155 ],
       [ 0.98935825,  0.6569866 ,  0.41211849,  0.90929743]])

In [47]:
np.cos(arr1)

array([[-0.65364362,  0.28366219, -0.65364362, -0.9899925 ],
       [-0.41614684, -0.91113026,  0.54030231,  0.96017029],
       [-0.14550003,  0.75390225, -0.91113026, -0.41614684]])

In [48]:
np.tan(arr1)

array([[ 1.15782128, -3.38051501,  1.15782128, -0.14254654],
       [-2.18503986, -0.45231566,  1.55740772, -0.29100619],
       [-6.79971146,  0.87144798, -0.45231566, -2.18503986]])

In [49]:
np.tanh(arr1)

array([[0.9993293 , 0.9999092 , 0.9993293 , 0.99505475],
       [0.96402758, 0.99999997, 0.76159416, 0.99998771],
       [0.99999977, 0.99999834, 0.99999997, 0.96402758]])

In [50]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.60205999, 0.47712125],
       [0.30103   , 0.95424251, 0.        , 0.77815125],
       [0.90308999, 0.84509804, 0.95424251, 0.30103   ]])

In [51]:
np.exp(arr1)

array([[5.45981500e+01, 1.48413159e+02, 5.45981500e+01, 2.00855369e+01],
       [7.38905610e+00, 8.10308393e+03, 2.71828183e+00, 4.03428793e+02],
       [2.98095799e+03, 1.09663316e+03, 8.10308393e+03, 7.38905610e+00]])

In [52]:
np.sqrt(arr1)

array([[2.        , 2.23606798, 2.        , 1.73205081],
       [1.41421356, 3.        , 1.        , 2.44948974],
       [2.82842712, 2.64575131, 3.        , 1.41421356]])

In [53]:
np.power(arr1,2)

array([[16, 25, 16,  9],
       [ 4, 81,  1, 36],
       [64, 49, 81,  4]])

In [54]:
np.mean(arr1)

5.0

In [55]:
np.median(arr1)

4.5

In [56]:
np.std(arr1)

2.6770630673681683

In [57]:
np.var(arr1)

7.166666666666667

In [58]:
np.min(arr1)

1

In [59]:
np.max(arr1)

9