![image](https://pwskills.com/images/PWSkills-main.png)

# Data Science Masters

## Day - 26
## Date- 26 February 2023 
## Numpy - III

## Sort, Search & Counting Functions.

In [1]:
import numpy as np

In [2]:
arr = np.array([4, 3, 4, 5, 6, 72, 3, 3, 455, 5, 6, 6])

In [3]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [4]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [5]:
np.searchsorted(arr, 34)

12

In [6]:
arr1 = np.array([0, 345, 454, 0, 0, 0, 0, 0])

In [7]:
np.count_nonzero(arr1)

2

In [8]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [9]:
np.where(arr > 6)

(array([5, 8]),)

In [10]:
np.extract(arr>3 , arr)

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

## Numpy - Byte Swapping.

In [11]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

## Numpy - Copies & Views

In [13]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [14]:
a = np.copy(arr)

In [15]:
b = arr.view()

In [16]:
b = arr

In [17]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [18]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
b[0] = 67

In [20]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

## Numpy - Matrix Library

In [22]:
import numpy.matlib as nm

In [23]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [24]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Numpy - Linear Algebra

In [26]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [27]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [28]:
np.dot()

TypeError: dot() missing 2 required positional arguments: 'a' and 'b'