![image](https://pwskills.com/images/PWSkills-main.png)

# Data Science Masters

## Day - 44
## Date- 19 March 2023 
## Feature Engineering- II

# 1. Feature Extraction
Feature Extraction is proccess of selection and extracting important features from raw data.

**ML Algorithm** $\rightarrow$ **1000 Feature** $\rightarrow$ **Most Important Features** $\rightarrow$ **Machine Learning Algorithm**

## 1.1 Feature Scaling
Feature scaling is a technique used to standardize the range of input variables or features in a dataset. It involves transforming the data so that it is on the same scale and has a similar range. Feature scaling is important because it can improve the performance of machine learning algorithms that use distance-based metrics or optimization algorithms that are sensitive to feature scales.

There are several methods for scaling features, including:

### 1.1.1 Standardization
This method scales the data to have zero mean and unit variance. Each feature is transformed to have a mean of zero and a standard deviation of one.

$$Standardization= \frac{(x - \bar{x})}{std(x)}$$

where,
<br> $x$ is the original feature value
<br> $\bar{x}$ is the mean of the feature values
<br> $std(x)$ is the standard deviation of the feature values.


### 1.1.2 Min-Max Scaling
This method scales the data to a fixed range, usually between 0 and 1. Each feature is transformed to have a minimum value of 0 and a maximum value of 1.

$$Min-Max Scaling= \frac{(x - min(x))} {(max(x) - min(x))}$$

where,
<br> $x$ is the original feature value
<br> $min(x)$ is the minimum value of the feature values <br> $max(x)$ is the maximum value of the feature values.

### 1.1.3 Max Abs Scaling
This method scales the data so that the maximum absolute value of each feature is 1.

$$Max Abs Scaling= \frac{x} {max(abs(x))}$$

where,
<br> $x$ is the original feature value 
<br> $max(abs(x))$ is the maximum absolute value of the feature values.

### 1.1.4 Robust Scaling
This method scales the data to be robust to outliers. It uses the interquartile range to scale the data so that it has a median of zero and a range that is proportional to the interquartile range.

$$Robust Scaling= \frac{(x - median(x))} {iqr(x)}$$

where,
<br> $x$ is the original feature value
<br> $median(x)$ is the median of the feature values
<br> $iqr(x)$ is the interquartile range of the feature values.


The choice of scaling method depends on the specific characteristics of the data and the requirements of the machine learning algorithm being used. In general, it is a good practice to scale the data before using it for machine learning to ensure that the algorithm performs optimally.

## 1.2 Feature Selection
We just pick the most important feature.

**500 Feature** $\rightarrow$ **Top 10 Features** $\rightarrow$ **ML Model Train**

### 1.2.1 Fitted Model

### 1.2.2 Embedded Method

### 1.2.3 Principal Component Analysis (PCA)

# 2. Feature Scaling

## 2.1 Standardization (Z-Score)
$$Z_{score}= \frac{x_i- \bar{x}} {\sigma}$$

$\mu= 0$ and $\sigma= 1$

## 2.2 Min Max Scaling (Normalization)
$0$ to $1$

$$x_{scaled}= \frac{x_i- x_{min}} {x_{max}- x_{min}}$$

## 2.3 Unit Vector
**Magnitude of 1**

$\overrightarrow{x}= (3, 4)$

$||\overrightarrow{x}||= \sqrt{(3)^2+ (4)^2}= \sqrt{25}= 5$

$\hat{\mu}= \Big(\frac{3}{||\overrightarrow{x}||}, \frac{4}{||\overrightarrow{x}||} \Big)= \Big(\frac{3}{5}, \frac{4}{5} \Big)$

$||\overrightarrow{\hat{\mu}}||= \sqrt{(3/5)^2+ (4/5)^2}= \sqrt{\frac{9+ 16}{25}}= \sqrt{\frac{25}{25}}= 1$

## 2.4 Standardization

In [1]:
import seaborn as sns

In [2]:
df= sns.load_dataset('tips')

In [3]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
total_bill= list(df['total_bill'])

In [5]:
total_bill

[16.99,
 10.34,
 21.01,
 23.68,
 24.59,
 25.29,
 8.77,
 26.88,
 15.04,
 14.78,
 10.27,
 35.26,
 15.42,
 18.43,
 14.83,
 21.58,
 10.33,
 16.29,
 16.97,
 20.65,
 17.92,
 20.29,
 15.77,
 39.42,
 19.82,
 17.81,
 13.37,
 12.69,
 21.7,
 19.65,
 9.55,
 18.35,
 15.06,
 20.69,
 17.78,
 24.06,
 16.31,
 16.93,
 18.69,
 31.27,
 16.04,
 17.46,
 13.94,
 9.68,
 30.4,
 18.29,
 22.23,
 32.4,
 28.55,
 18.04,
 12.54,
 10.29,
 34.81,
 9.94,
 25.56,
 19.49,
 38.01,
 26.41,
 11.24,
 48.27,
 20.29,
 13.81,
 11.02,
 18.29,
 17.59,
 20.08,
 16.45,
 3.07,
 20.23,
 15.01,
 12.02,
 17.07,
 26.86,
 25.28,
 14.73,
 10.51,
 17.92,
 27.2,
 22.76,
 17.29,
 19.44,
 16.66,
 10.07,
 32.68,
 15.98,
 34.83,
 13.03,
 18.28,
 24.71,
 21.16,
 28.97,
 22.49,
 5.75,
 16.32,
 22.75,
 40.17,
 27.28,
 12.03,
 21.01,
 12.46,
 11.35,
 15.38,
 44.3,
 22.42,
 20.92,
 15.36,
 20.49,
 25.21,
 18.24,
 14.31,
 14.0,
 7.25,
 38.07,
 23.95,
 25.71,
 17.31,
 29.93,
 10.65,
 12.43,
 24.08,
 11.69,
 13.42,
 14.26,
 15.95,
 12.48,
 29.8,
 8.52,

In [9]:
import numpy as np
mean= np.mean(total_bill)
std= np.std(total_bill)

In [10]:
mean, std

(19.78594262295082, 8.884150577771132)

In [11]:
normalized_data=[]
for i in total_bill:
    z_score=(i-mean)/std ## z_score
    normalized_data.append(z_score)
    
print(normalized_data)

[-0.3147113050904943, -1.0632353132988692, 0.13777989987156145, 0.43831510316725475, 0.540744704290506, 0.6195367051545455, -1.2399545152367863, 0.7985071071171495, -0.5342033074974614, -0.5634689078183903, -1.0711145133852733, 1.7417599174609364, -0.49143050702841123, -0.15262490331304146, -0.557840907756673, 0.2019391005751361, -1.0643609133112126, -0.3935033059545337, -0.31696250511518104, 0.09725829942719795, -0.2100305039425557, 0.05673669898283484, -0.45203450659639155, 2.2100095225958003, 0.003833498402694168, -0.2224121040783337, -0.7221785095588127, -0.7987193103981653, 0.21544630072325727, -0.015301701807144186, -1.1521577142739994, -0.16162970341178864, -0.5319521074727743, 0.10176069947657193, -0.22578890411536368, 0.4810879036363046, -0.3912521059298469, -0.32146490516455467, -0.12335930299211233, 1.2926455125359115, -0.4216433062631192, -0.2618081045103532, -0.6580193088552376, -1.137524914113535, 1.1947183114620337, -0.16838330348584943, 0.2751031013774587, 1.41983831393

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
scaler= StandardScaler()
scaler

StandardScaler()

In [16]:
scaler.fit(df[['total_bill', 'tip']])

StandardScaler()

In [17]:
import pandas as pd
pd.DataFrame(scaler.transform(df[['total_bill', 'tip']]), columns=['total_bill', 'tips'])

total_bill      tips
0     -0.314711 -1.439947
1     -1.063235 -0.969205
2      0.137780  0.363356
3      0.438315  0.225754
4      0.540745  0.443020
..          ...       ...
239    1.040511  2.115963
240    0.832275 -0.722971
241    0.324630 -0.722971
242   -0.221287 -0.904026
243   -0.113229  0.001247

[244 rows x 2 columns]

# 3. Normalization (Min Max Scaler)

In [18]:
import seaborn as sns

df= sns.load_dataset('taxis')
df.head()

pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15   
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
min_max=MinMaxScaler()
min_max

MinMaxScaler()

In [21]:
min_max.fit(df[['distance','fare','tip']])

MinMaxScaler()

In [22]:
min_max.transform(df[['distance', 'fare', 'tip']])

array([[0.04359673, 0.04026846, 0.06475904],
       [0.02152589, 0.02684564, 0.        ],
       [0.0373297 , 0.04362416, 0.07108434],
       ...,
       [0.11280654, 0.10067114, 0.        ],
       [0.03051771, 0.03355705, 0.        ],
       [0.10490463, 0.09395973, 0.10120482]])

In [23]:
min_max.fit_transform(df[['distance', 'fare', 'tip']])

array([[0.04359673, 0.04026846, 0.06475904],
       [0.02152589, 0.02684564, 0.        ],
       [0.0373297 , 0.04362416, 0.07108434],
       ...,
       [0.11280654, 0.10067114, 0.        ],
       [0.03051771, 0.03355705, 0.        ],
       [0.10490463, 0.09395973, 0.10120482]])

In [24]:
min_max.transform([[1, 3, 4]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.02724796, 0.01342282, 0.12048193]])

# 4. Unit Vector

In [25]:
import seaborn as sns

df= sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [26]:
from sklearn.preprocessing import normalize

In [27]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [28]:
normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])

array([[0.80377277, 0.55160877, 0.22064351, 0.0315205 ],
       [0.82813287, 0.50702013, 0.23660939, 0.03380134],
       [0.80533308, 0.54831188, 0.2227517 , 0.03426949],
       [0.80003025, 0.53915082, 0.26087943, 0.03478392],
       [0.790965  , 0.5694948 , 0.2214702 , 0.0316386 ],
       [0.78417499, 0.5663486 , 0.2468699 , 0.05808704],
       [0.78010936, 0.57660257, 0.23742459, 0.0508767 ],
       [0.80218492, 0.54548574, 0.24065548, 0.0320874 ],
       [0.80642366, 0.5315065 , 0.25658935, 0.03665562],
       [0.81803119, 0.51752994, 0.25041771, 0.01669451],
       [0.80373519, 0.55070744, 0.22325977, 0.02976797],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.82307218, 0.51442011, 0.24006272, 0.01714734],
       [0.8025126 , 0.55989251, 0.20529392, 0.01866308],
       [0.81120865, 0.55945424, 0.16783627, 0.02797271],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.79428944, 0.57365349, 0.19121783, 0.05883625],
       [0.80327412, 0.55126656,

In [29]:
import pandas as pd
pd.DataFrame(normalize(df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]),
             columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])

sepal_length  sepal_width  petal_length  petal_width
0        0.803773     0.551609      0.220644     0.031521
1        0.828133     0.507020      0.236609     0.033801
2        0.805333     0.548312      0.222752     0.034269
3        0.800030     0.539151      0.260879     0.034784
4        0.790965     0.569495      0.221470     0.031639
..            ...          ...           ...          ...
145      0.721557     0.323085      0.560015     0.247699
146      0.729654     0.289545      0.579090     0.220054
147      0.716539     0.330710      0.573231     0.220474
148      0.674671     0.369981      0.587616     0.250281
149      0.690259     0.350979      0.596665     0.210588

[150 rows x 4 columns]

# 5. Principal Component Analysis (PCA)

![img](https://i.ytimg.com/vi/QP43Iy-QQWY/maxresdefault.jpg)