![image](https://pwskills.com/images/PWSkills-main.png)

# Data Science Masters

## Statistics Assignments - 7

### Date : 12 - Mar - 2023

**Q1 :** Calculate the 95% confidence interval for a sample of data with a mean of 50 and a standard deviation of 5 using Python. Interpret the results.

**Ans :** To calculate the 95% confidence interval for a sample of data with a mean of 50 and a standard deviation of 5 using Python, we can use the scipy.stats module. Specifically, we can use the t.interval() function from this module, which calculates the confidence interval for a given sample mean, sample size, and confidence level, assuming that the underlying population follows a normal distribution.

Here's the Python code to calculate the 95% confidence interval for the given sample data:

In [2]:
import scipy.stats as stats
import numpy as np
sample_mean = 50
sample_std = 5
sample_size = 100 # assuming a sample size of 100 for illustration purposes

# Calculate the 95% confidence interval using the t-distribution
ci = stats.t.interval(0.95, df=sample_size-1, loc=sample_mean, scale=sample_std/np.sqrt(sample_size))

# Print the results
print(f"The 95% confidence interval is {ci}")

The 95% confidence interval is (49.00789152424566, 50.99210847575434)


**Q2 :** Conduct a chi-square goodness of fit test to determine if the distribution of colors of M&Ms in a bag matches the expected distribution of 20% blue, 20% orange, 20% green, 10% yellow, 10% red, and 20% brown. Use Python to perform the test with a significance level of 0.05.

**Ans :** To conduct a chi-square goodness of fit test in Python, we can use the scipy.stats module. Specifically, we can use the chisquare() function from this module, which calculates the chi-square test statistic and p-value for a given set of observed and expected frequencies.

Here's the Python code to conduct a chi-square goodness of fit test for the distribution of colors of M&Ms in a bag:

In [4]:
import numpy as np
import scipy.stats as stats

# Observed frequencies
obs = np.array([48, 27, 24, 15, 10, 16])

# Expected frequencies (assuming equal distribution of colors)
exp = np.array([0.2, 0.2, 0.2, 0.1, 0.1, 0.2]) * np.sum(obs)

# Calculate the chi-square test statistic and p-value
stat, pval = stats.chisquare(obs, f_exp=exp)

# Print the results
print(f"The chi-square test statistic is {stat:.3f}")
print(f"The p-value is {pval:.3f}")

if pval < 0.05:
    print("We reject the null hypothesis that the observed distribution of colors matches the expected distribution.")
else:
    print("We fail to reject the null hypothesis that the observed distribution of colors matches the expected distribution.")


The chi-square test statistic is 21.250
The p-value is 0.001
We reject the null hypothesis that the observed distribution of colors matches the expected distribution.


**Q3 :**  Use Python to calculate the chi-square statistic and p-value for a contingency table with the following data:

|           | **Group A** | **Group B** |
| --------- | ----------- | ----------- |
| Outcome 1 |    20       |      15     |
| Outcome 2 |    10       |      25     |
| Outcome 3 |    15       |      20     |

Interpret the results of the test.

**Ans :**

In [15]:
import numpy as np
from scipy.stats import chi2_contingency

# Define the contingency table
observed = np.array([[20, 15], [10, 25], [15, 20]])

# Calculate the chi-square statistic, p-value, degrees of freedom, and expected frequencies
chi2, p, dof, expected = chi2_contingency(observed)

# Print the results
print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:\n", expected)


Chi-square statistic: 5.833333333333334
P-value: 0.05411376622282158
Degrees of freedom: 2
Expected frequencies:
 [[15. 20.]
 [15. 20.]
 [15. 20.]]


**Q4 :** A study of the prevalence of smoking in a population of 500 individuals found that 60 individuals smoked. Use Python to calculate the 95% confidence interval for the true proportion of individuals in the population who smoke.

**Ans :** To calculate the 95% confidence interval for the true proportion of individuals in the population who smoke, we can use the formula:

CI = p ± z*(sqrt(p*(1-p)/n))

Where:

p is the sample proportion (number of individuals who smoke divided by the total sample size)
z is the critical value from the standard normal distribution for the desired confidence level (95% confidence level corresponds to z=1.96)
n is the sample size
Using Python, we can calculate this as follows:

In [3]:
import math

# sample size
n = 500

# number of individuals who smoke
x = 60

# sample proportion
p = x/n

# critical value for 95% confidence level
z = 1.96

# calculate standard error
se = math.sqrt(p*(1-p)/n)

# calculate confidence interval
lower = p - z*se
upper = p + z*se

print("95% Confidence Interval: ({:.4f}, {:.4f})".format(lower, upper))


95% Confidence Interval: (0.0915, 0.1485)


**Q5 :** Calculate the 90% confidence interval for a sample of data with a mean of 75 and a standard deviation of 12 using Python. Interpret the results.

**Ans :** To calculate the 90% confidence interval for a sample of data with a mean of 75 and a standard deviation of 12, we can use the formula:

CI = x̄ ± z*(s/√n)

Where:

x̄ is the sample mean
<br> s is the sample standard deviation
<br> n is the sample size
<br> z is the critical value from the standard normal distribution for the desired confidence level (90% confidence level corresponds to z=1.645)

Using Python, we can calculate this as follows:

In [5]:
import math

# sample mean
x_bar = 75

# sample standard deviation
s = 12

# sample size
n = 100

# critical value for 90% confidence level
z = 1.645

# calculate standard error
se = s/math.sqrt(n)

# calculate confidence interval
lower = x_bar - z*se
upper = x_bar + z*se

print("90% Confidence Interval: ({:.4f}, {:.4f})".format(lower, upper))


90% Confidence Interval: (73.0260, 76.9740)


**Q6 :** Use Python to plot the chi-square distribution with 10 degrees of freedom. Label the axes and shade the area corresponding to a chi-square statistic of 15.

**Ans :**

In [6]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2

# degrees of freedom
df = 10

# x-values for the plot
x = np.linspace(0, 30, 500)

# probability density function values
pdf = chi2.pdf(x, df)

# create the plot
fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(x, pdf, color='black', linewidth=2)

# shade the area corresponding to a chi-square statistic of 15
x_shade = np.linspace(15, 30, 500)
ax.fill_between(x_shade, chi2.pdf(x_shade, df), color='blue', alpha=0.3)

# add labels and a title
ax.set_xlabel('Chi-Square Statistic')
ax.set_ylabel('Probability Density')
ax.set_title('Chi-Square Distribution with 10 Degrees of Freedom')

# show the plot
plt.show()


**Q7 :** A random sample of 1000 people was asked if they preferred Coke or Pepsi. Of the sample, 520 preferred Coke. Calculate a 99% confidence interval for the true proportion of people in the population who prefer Coke.

**Ans :**

In [7]:
import math

# sample size
n = 1000

# number of individuals who prefer Coke
x = 520

# sample proportion
p = x/n

# critical value for 99% confidence level
z = 2.576

# calculate standard error
se = math.sqrt(p*(1-p)/n)

# calculate confidence interval
lower = p - z*se
upper = p + z*se

print("99% Confidence Interval: ({:.4f}, {:.4f})".format(lower, upper))


99% Confidence Interval: (0.4793, 0.5607)


**Q8 :** A researcher hypothesizes that a coin is biased towards tails. They flip the coin 100 times and observe 45 tails. Conduct a chi-square goodness of fit test to determine if the observed frequencies match the expected frequencies of a fair coin. Use a significance level of 0.05.

**Ans :**

In [9]:
import scipy.stats as stats

# Define null hypothesis, alternative hypothesis, and significance level
null_hypothesis = "The coin is fair."
alternative_hypothesis = "The coin is biased towards tails."
significance_level = 0.05

# Define observed values and expected values
observed_values = [45, 55]  # 45 tails, 55 heads
expected_values = [50, 50]  # assuming a fair coin

# Calculate the chi-square statistic and p-value
chi_square_statistic, p_value = stats.chisquare(observed_values, expected_values)

# Compare p-value to significance level to determine whether to reject null hypothesis
if p_value < significance_level:
    print(f"Reject the null hypothesis. {alternative_hypothesis}")
else:
    print(f"Fail to reject the null hypothesis. {null_hypothesis}")


Fail to reject the null hypothesis. The coin is fair.


**Q9 :** A study was conducted to determine if there is an association between smoking status (smoker or non-smoker) and lung cancer diagnosis (yes or no). The results are shown in the contingency table below. Conduct a chi-square test for independence to determine if there is a significant association between smoking status and lung cancer diagnosis.

|            | **Lung Cancer : `Yes`** | **Lung Cancer : `No`** |
| ---------- | ----------------------- | ---------------------- |
| Smoker     |    60                   |       140              |
| Non-Smoker |    30                   |      170               |

**Ans :**

In [8]:
import scipy.stats as stats
import numpy as np

# Create the contingency table
obs = np.array([[60, 140], [30, 170]])

# Calculate the chi-square test statistic, p-value, degrees of freedom and expected frequencies
chi2_stat, p_val, dof, expected_freq = stats.chi2_contingency(obs)

# Print the results
print("Chi-square test statistic: ", chi2_stat)
print("Degrees of freedom: ", dof)
print("P-value: ", p_val)
print("Expected frequencies: \n", expected_freq)


Chi-square test statistic:  12.057347670250895
Degrees of freedom:  1
P-value:  0.0005158863863703744
Expected frequencies: 
 [[ 45. 155.]
 [ 45. 155.]]


**Q10 :** A study was conducted to determine if the proportion of people who prefer milk chocolate, dark chocolate, or white chocolate is different in the U.S. versus the U.K. A random sample of 500 people from the U.S. and a random sample of 500 people from the U.K. were surveyed. The results are shown in the contingency table below. Conduct a chi-square test for independence to determine if there is a significant association between chocolate preference and country of origin.

|                  | **Milk Chocolate** | **Dark Chocolate** |
| ---------------- | ------------------ | ------------------ |
| U.S. (n=500)     |    200             |       150          |
| U.K. (n=500)     |    225             |       175          |

**Ans :**

In [10]:
import numpy as np
import scipy.stats as stats

# Define null hypothesis, alternative hypothesis, and significance level
null_hypothesis = "There is no association between chocolate preference and country of origin."
alternative_hypothesis = "There is an association between chocolate preference and country of origin."
significance_level = 0.01

# Define observed values
observed_values = np.array([[200, 150, 150], [225, 175, 100]])

# Calculate expected values
row_totals = observed_values.sum(axis=1)
column_totals = observed_values.sum(axis=0)
sample_size = observed_values.sum()
expected_values = np.outer(row_totals, column_totals) / sample_size

# Calculate the chi-square statistic and p-value
chi_square_statistic, p_value, _, _ = stats.chi2_contingency(observed_values)

# Compare p-value to significance level to determine whether to reject null hypothesis
if p_value < significance_level:
    print(f"Reject the null hypothesis. {alternative_hypothesis}")
else:
    print(f"Fail to reject the null hypothesis. {null_hypothesis}")

# Print the observed and expected values, and the chi-square statistic and p-value
print("Observed values:")
print(observed_values)
print("Expected values:")
print(expected_values)
print(f"Chi-square statistic: {chi_square_statistic}")
print(f"P-value: {p_value}")

Reject the null hypothesis. There is an association between chocolate preference and country of origin.
Observed values:
[[200 150 150]
 [225 175 100]]
Expected values:
[[212.5 162.5 125. ]
 [212.5 162.5 125. ]]
Chi-square statistic: 13.393665158371041
P-value: 0.0012348168997745918


**Q11 :** A random sample of 30 people was selected from a population with an unknown mean and standard deviation. The sample mean was found to be 72 and the sample standard deviation was found to be 10. Conduct a hypothesis test to determine if the population mean is significantly different from 70. Use a significance level of 0.05.

**Ans :**

In [14]:
import scipy.stats as stats

# Define null hypothesis, alternative hypothesis, and significance level
null_hypothesis = "The population mean is equal to 70."
alternative_hypothesis = "The population mean is not equal to 70."
significance_level = 0.05

# Define sample mean, sample standard deviation, sample size, and hypothesized population mean
sample_mean = 72
sample_std_dev = 10
sample_size = 30
hypothesized_mean = 70

# Calculate the t-statistic and p-value
t_statistic, p_value = stats.ttest_1samp([sample_mean], hypothesized_mean)

# Compare p-value to significance level to determine whether to reject null hypothesis
if p_value < significance_level:
    print(f"Reject the null hypothesis. {alternative_hypothesis}")
else:
    print(f"Fail to reject the null hypothesis. {null_hypothesis}")

# Print the t-statistic, p-value, and 95% confidence interval for the population mean
print(f"t-statistic: {t_statistic}")
print(f"p-value: {p_value}")
print(f"95% confidence interval for population mean: {stats.t.interval(0.95, sample_size-1, loc=sample_mean, scale=sample_std_dev/np.sqrt(sample_size))}")

Fail to reject the null hypothesis. The population mean is equal to 70.
t-statistic: nan
p-value: nan
95% confidence interval for population mean: (68.265938632419, 75.734061367581)


/tmp/ipykernel_77/2784087827.py:15: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  t_statistic, p_value = stats.ttest_1samp([sample_mean], hypothesized_mean)
/opt/conda/lib/python3.10/site-packages/scipy/stats/_stats_py.py:1253: RuntimeWarning: divide by zero encountered in divide
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
/opt/conda/lib/python3.10/site-packages/scipy/stats/_stats_py.py:1253: RuntimeWarning: invalid value encountered in double_scalars
  var *= np.divide(n, n-ddof)  # to avoid error on division by zero
